#pragma once

#include <glad/glad.h>

#define GL_DEBUG_MESSAGE_MIN_SEVERITY GL_DEBUG_SEVERITY_NOTIFICATION

#define WINDOW_WIDTH 1200
#define WINDOW_HEIGHT 1200

// (0, 0) is at the bottom-left corner
#define COORDINATE_SPACE 4096
#define COORDINATE_SCALING (COORDINATE_SPACE / 1000.0f)

#define PADDLE_WIDTH (150.0f * COORDINATE_SCALING)
#define PADDLE_HEIGHT (50.0f * COORDINATE_SCALING)
#define PADDLE_START_POS_X (COORDINATE_SPACE / 2.0f - PADDLE_WIDTH / 2.0f)
#define PADDLE_START_POS_Y (COORDINATE_SPACE / 6.0f)
#define PADDLE_SPEED (500.0f * COORDINATE_SCALING)

#define BALL_START_POS_X (COORDINATE_SPACE / 2.0f - PADDLE_WIDTH / 2.0f)
#define BALL_START_POS_Y (COORDINATE_SPACE / 4.0f)
#define BALL_RADIUS (20.0f * COORDINATE_SCALING)
#define BALL_DIRECTION (1.0f)
#define BALL_SPEED (1.0f)

#define FLOATS_PER_BLOCK_VERTEX 2